### ISSUE TITLE
Suggestion: Add github pages deployment at the sidebar (about section) of your github repo

### ISSUE THREAD

**Issue by mithi** [fuddl/bare-minimum-text-marker#4]
Suggestion: Add github pages deployment at the sidebar (about section) of your github repo

Currently it says 
> No description, website, or topics provided

<img width="1265" alt="Screen Shot 2021-03-28 at 4 52 22 PM" src="https://user-images.githubusercontent.com/1670421/112747192-48b4f180-8fe6-11eb-9afb-f398d71445bd.png">

I suggest you add https://fuddl.github.io/bare-minimum-text-marker/
so more people can see. 

I really love that it the orientation of the cube follows the mouse pointer position. It's really cool! I already added a link to this project on the README of `bare-minimum-2d`

Can I ask how you found `bare-minimum-2d` and `bare-minimum-3d` by the way?

Also, looking forward to seeing more demos of using other marks, font families, colors etc.

**Comment by fuddl** [comment]
> Suggestion: Add github pages deployment at the sidebar (about section) of your github repo
> 
> Currently it says
> 
> > No description, website, or topics provided
>
> I suggest you add https://fuddl.github.io/bare-minimum-text-marker/
> so more people can see.

I did this.
 
> I really love that it the orientation of the cube follows the mouse pointer position. It's really cool! I already added a link to this project on the README of `bare-minimum-2d`

Thanks 😀. In a different project I used a grabbing navigation. Like in a [map application](https://www.openstreetmap.org/). unfortunately, non of these methods works on touch devices.

> Can I ask how you found `bare-minimum-2d` and `bare-minimum-3d` by the way?

I wanted something like [plotly](https://www.npmjs.com/package/plotly.js) but with the ability to draw two-dimensionally, ideally in svg. so think i've been browsing [plotly's keywords](https://www.npmjs.com/search?q=keywords:graphing) and [your demo](https://mithi.github.io/hello-3d-world/) was quote convincing.

> Also, looking forward to seeing more demos of using other marks, font families, colors etc.

if you have ideas or data to plot, let me know.
